# Generated by Django 4.2.6 on 2023-11-02 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cid_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grievance_type', models.CharField(max_length=1)),
                ('sex_type', models.CharField(max_length=1)),
                ('stadium_stype', models.CharField(max_length=1)),
                ('irradiated_fields_value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cid_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cid_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('grievance_type', models.CharField(max_length=1)),
                ('sex_type', models.CharField(max_length=1)),
                ('stadium_stype', models.CharField(max_length=1)),
                ('irradiated_fields_value', models.IntegerField()),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cids_history', to='cbo.cid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('occupation_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('occupation_code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=150, null=True)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_history', to='cbo.occupation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('procedure_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('complexity_type', models.CharField(max_length=1, null=True)),
                ('sex_type', models.CharField(max_length=1, null=True)),
                ('maximum_execution_amount', models.IntegerField(null=True)),
                ('stay_day_number', models.CharField(max_length=4, null=True)),
                ('points_number', models.IntegerField(null=True)),
                ('minimum_age_value', models.IntegerField(null=True)),
                ('maximum_age_value', models.IntegerField(null=True)),
                ('SH_value', models.IntegerField(null=True)),
                ('SA_value', models.IntegerField(null=True)),
                ('SP_value', models.IntegerField(null=True)),
                ('stay_time_number', models.IntegerField(null=True)),
                ('competence_date', models.CharField(max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure_has_cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('st_principal', models.CharField(max_length=4)),
                ('competence_date', models.CharField(max_length=6)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cids_has_procedure', to='cbo.cid')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_cid', to='cbo.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure_has_occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competence_date', models.CharField(max_length=6)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_has_procedure', to='cbo.occupation')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_occupation', to='cbo.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure_has_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competence_date', models.CharField(max_length=6)),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_record', to='cbo.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('competence_date', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('CPF', models.CharField(max_length=11)),
                ('specialty', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('telephone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('CRM', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('competence_date', models.CharField(max_length=6)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_history', to='cbo.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('procedure_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250, null=True)),
                ('complexity_type', models.CharField(max_length=1, null=True)),
                ('sex_type', models.CharField(max_length=1, null=True)),
                ('maximum_execution_amount', models.IntegerField(null=True)),
                ('stay_day_number', models.CharField(max_length=4, null=True)),
                ('points_number', models.IntegerField(null=True)),
                ('minimum_age_value', models.IntegerField(null=True)),
                ('maximum_age_value', models.IntegerField(null=True)),
                ('SH_value', models.IntegerField(null=True)),
                ('SA_value', models.IntegerField(null=True)),
                ('SP_value', models.IntegerField(null=True)),
                ('stay_time_number', models.IntegerField(null=True)),
                ('competence_date', models.CharField(max_length=6, null=True)),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_history', to='cbo.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure_has_record_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competence_date', models.CharField(max_length=6)),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_record', to='cbo.procedure_history')),
                ('procedure_has_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbo.procedure_has_record')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_has_procedure', to='cbo.record_history')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='procedure_has_record',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_has_procedure', to='cbo.record'),
        ),
        migrations.CreateModel(
            name='Procedure_has_occupation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competence_date', models.CharField(max_length=6)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_has_procedure', to='cbo.occupation_history')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_occupation', to='cbo.procedure_history')),
                ('procedure_has_occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbo.procedure_has_occupation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure_has_cid_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('st_principal', models.CharField()),
                ('competence_date', models.CharField(max_length=6)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cids_has_procedure', to='cbo.cid_history')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_cid', to='cbo.procedure_history')),
                ('procedure_has_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbo.procedure_has_cid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='occupation_history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_history', to='cbo.user'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='cbo.user'),
        ),
    ]
