# Generated by Django 4.2.6 on 2023-10-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cid',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='cid_history',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='record',
        ),
        migrations.RemoveField(
            model_name='procedure_history',
            name='record',
        ),
    ]
