# Generated by Django 4.2.6 on 2023-10-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0002_remove_cid_procedure_remove_cid_history_procedure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cid',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='cid_history',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='occupation_history',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure_has_cid',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure_has_cid_history',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure_has_occupation',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure_has_occupation_history',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure_has_record',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='procedure_has_record_history',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='record_history',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_update',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='procedure_history',
            name='last_update',
        ),
        migrations.AddField(
            model_name='procedure_history',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
