# Generated by Django 4.2.6 on 2023-11-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0002_cid_cbo_cid_cid_cod_c08b9e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='occupation',
            name='cbo_occupat_occupat_bda372_idx',
        ),
        migrations.RemoveIndex(
            model_name='occupation_history',
            name='cbo_occupat_occupat_119b14_idx',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='occupation_history',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='cbo.occupation'),
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['occupation_code', 'name'], name='cbo_occupat_occupat_17e032_idx'),
        ),
        migrations.AddIndex(
            model_name='occupation_history',
            index=models.Index(fields=['occupation_code', 'name', 'occupation'], name='cbo_occupat_occupat_48316a_idx'),
        ),
    ]
