# Generated by Django 4.2.6 on 2023-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0003_rename_last_update_cid_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cid_history',
            name='cid_code',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occupation_history',
            name='occupation_code',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='procedure_history',
            name='procedure_code',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record_history',
            name='record_code',
            field=models.AutoField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
