# Generated by Django 4.2.6 on 2023-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0004_alter_cid_history_cid_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cid_history',
            name='cid_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occupation_history',
            name='occupation_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='procedure_has_cid_history',
            name='st_principal',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='procedure_history',
            name='procedure_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record_history',
            name='record_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
