# Generated by Django 4.2.6 on 2023-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0004_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
